language: python
python: 3.6

sudo: required
dist: trusty

services:
  - redis-server

branches:
  only:
    - master

matrix:
  fast_finish: true
  include:

    - os: linux
      python: "2.7"
      sudo: required
      dist: trusty
      env:
        - TOX_ENV=py27

    - os: linux
      python: "3.5"
      sudo: required
      dist: trusty
      env:
        - TOX_ENV=py35

    - os: linux
      python: "3.6"
      sudo: required
      dist: trusty
      env:
        - TOX_ENV=py36

install:
- pip install tox

script:
    tox -e $TOX_ENV
